<?php
/**
* @file: breadcrumb.phtml
* @author: huuthanh3108@gmaill.com
* @date: 29-10-2012
* @company : http://dnict.vn
**/
if (null === $this->container) {
	$this->container = $this->breadcrumbs()->getContainer();
}

// find deepest active
if (!$active = $this->breadcrumbs()->findActive($this->container)) {
	return '';
}

$active = $active['page'];

// put the deepest active page last in breadcrumbs
if ($this->breadcrumbs()->getLinkLast()) {
	$html = ' <li class="current">' . $this->breadcrumbs()->htmlify($active) . '</li>' . PHP_EOL;
} else {
	$html = $active->getLabel();
	if ($this->breadcrumbs()->getUseTranslator() && $t = $this->breadcrumbs()->getTranslator()) {
		$html = $t->translate($html);
	}
	$html = ' <li class="current">' . $this->escape($html) . '</li>' . PHP_EOL;
}

// walk back to root
while (($parent = $active->getParent()) != null) {
	if ($parent instanceof Zend_Navigation_Page) {
		// prepend crumb to html
		$html = ' <li>' . $this->breadcrumbs()->htmlify($parent) . '</li>' . PHP_EOL . $html;
	}

	if ($parent === $this->container) {
		// at the root of the given container
		break;
	}

	$active = $parent;
}
echo strlen($html) ? $this->breadcrumbs()->getIndent() . '<div class="bc"><ul id="breadcrumbs" class="breadcrumbs"></li>' . PHP_EOL
. $html .  '</ul></div>' . PHP_EOL : '';
?>