<script>

jQuery(function($){
	$("input#submit").mouseout(function () {	    
		jQuery(this).css('padding','0px');
		jQuery(this).css('background','white');
		jQuery(this).css('color','black');     
		                                           	         		
     });  
	 $("input#submit").mouseover(function () {
		jQuery(this).css('padding','3px');   
		jQuery(this).css('background','black');
		jQuery(this).css('color','white');                                    	         		
     });

	 $("a.close").mouseout(function () {	    
			jQuery(this).css('padding','0px');
			
			                                           	         		
	     });  
		 $("a.close").mouseover(function () {
			jQuery(this).css('padding','3px');   
			                            	         		
	     });
	
    jQuery("#password").focus();
    jQuery("input#submit").click(function () {
        if(!validate())
            return;
    	<?php echo 'url="'.$this->baseUrl('/admin/index/ajaxchangepassword').'";';?>    	
    	jQuery.post(url,{'oldPassword':jQuery('input#password').val(),'newPassword':jQuery('input#newPassword').val()},function(resp){
        	if(resp==''){
            	alert('Thành công');
        		window.location="<?php echo $this->baseUrl('/admin/index/index');?>";
        	}
        	else if(resp=='error'){
            	jQuery('div#thongBao').html('Nhập không đúng password cũ.');
        	}
          	           	    				
    	});     	         	         		
    });
    
});
function validate(){	
	oldPassword=document.getElementById('password');
	newPassword=document.getElementById('newPassword');
	confirmNewPassword=document.getElementById('confirmNewPassword');	
	if(oldPassword.value==null||oldPassword.value==""){
		oldPassword.setAttribute('style',"border-color: red;");
		oldPassword.focus();
		return false;
	}
	if(newPassword.value==null||newPassword.value==""){
		newPassword.setAttribute('style',"border-color: red;");
		newPassword.focus();
		return false;
	}
	if(newPassword.value.indexOf(" ",0)!=-1){
		newPassword.setAttribute('style',"border-color: red;");
		newPassword.focus(); 
		return false;
	}
	if(confirmNewPassword.value==null||confirmNewPassword.value==""){
		confirmNewPassword.setAttribute('style',"border-color: red;");
		confirmNewPassword.focus();
		return false;
	}
	if(newPassword.value!=confirmNewPassword.value){
		alert("Việc nhập password mới 2 lần không trùng nhau.");
		newPassword.setAttribute('style',"border-color: red;");
		confirmNewPassword.setAttribute('style',"border-color: red;");
		newPassword.focus();
		return false;
	}
	return true;
}  
</script>
<div id="thongBao" style="padding-left: 100px;color: red;">  
</div>
<div style="float: left;text-align: right;padding-left: 100px;width: 300px;">Nhập password cũ:</div>
<div style="float: left;"><input id="password" type="password" name="oldPassword"/></div>
<div style="clear: both;"></div>
<div style="float: left;text-align: right;padding-left: 100px;width: 300px;margin-top: 10px;">Nhập password mới:</div>
<div style="float: left;margin-top: 10px;"><input type="password" name="newPassword" id="newPassword"/></div>
<div style="clear: both;"></div>
<div style="float: left;text-align: right;padding-left: 100px;width: 300px;margin-top: 10px;">Nhập lại password mới:</div>
<div style="float: left;margin-top: 10px;"><input type="password" name="confirmNewPassword" id="confirmNewPassword"/></div>
<div style="clear: both;"></div>
<div style="margin-left: 350px;margin-top: 10px;"><input style="cursor: pointer;background: white;color: black;width: 100px;" type="button" value="Đổi" id="submit"/></div>
