
<table width="100%">
   <tbody>       
       <tr>
           <td align="right">password:</td>
           <td align="left"><input size="20" type="password" name="password"/><font style="color: red;">*</font></td>
       </tr>
       <tr>
           <td align="right">Nhập lại password:</td>
           <td align="left"><input size="20" type="password" name="confirm_password"/><font style="color: red;">*</font></td>
       </tr>       
   </tbody>
</table> 
