<script type="text/javascript">
function save(){	
	document.form1.submit(); 
}
</script>
<?php
$message=$this->message;
if($message!=""){
?>
<div class="row-fluid" style="margin-top: 20px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='color: red;'>
        <?php
        echo $message;
        ?>
    </div>
    <div class="span3">&nbsp;</div>
</div>
<?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
	  <div style="float: left;"></div>
	  <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
	  <div style="clear: both;"></div>
	</div>
        
    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form1" id="form1" action="<?php echo $this->url();?>" method="post">
<div class="row-fluid">
    <div class="span12" style="padding-top: 20px;">
        <table border="1" style="width: 100%">
            <thead>
                <tr>
                    <th>Tiếng Việt</th>
                    <th>Tiếng Trung</th>
                    <th>Tiếng Anh</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $data=$this->data;
                for($i=0;$i<count($data);$i++){
                ?>
                <tr>
                    <td>
                        <input type="text" name="text_vi[]" value="<?php echo $data[$i]["text_vi"];?>">                        
                    </td>
                    <td>
                        <input type="text" name="text_cn[]" value="<?php echo $data[$i]["text_cn"];?>">
                    </td>
                    <td>
                        <input type="text" name="text_en[]" value="<?php echo $data[$i]["text_en"];?>">
                    </td>
                </tr>
            <input type="hidden" name="id[]" value="<?php echo $data[$i]["id"];?>"/>
                <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
</form>
