<?php
/**
* @file: xhtml.phtml
* @author: huuthanh3108@gmaill.com
* @date: 31-10-2012
* @company : http://dnict.vn
**/
?>
<!-- CUSTOM WIDGET : begin -->
<div class="span3">
	<div class="custom">
		<p>
			<img src="/assets/dummies/logo2_footer.png" alt="">
		</p>
		<p>An dicit albucius usu, pri ad suscipit principes. Atqui primis
			recteque nec in. Pri reque adversarium te.</p>
		<address>
			123 Our Street, District 600<br> Los Angeles, CA 94107
		</address>
	</div>
</div>
<!-- CUSTOM WIDGET : end -->
<!-- CONTACT WIDGET : begin -->
<div class="span9">
	<div class="widget contact">
		<h3>
			<span>Liên hệ</span> <a href="#" class="more">more</a>
		</h3>
		<div class="content">
			<ul class="contact-list">
				<li class="mail"><strong><a href="mailto:hocongthanh5887@yahoo.com">hocongthanh5887@yahoo.com</a></strong></li>
				<li class="phone"><strong><span><em>0905030505 - 0913484800</em></span></strong></li>				
			</ul>
		</div>
	</div>
</div>
<!-- CONTACT WIDGET : end -->