<script type="text/javascript">
    function save() {
        document.form.submit();
    }
    function backItemIndex() {
        url = "<?php echo $this->baseUrl('/admin/question/'); ?>";
        window.location = url;
    }

</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">	  
            <div onclick="save();" style="float: right;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>
            <div onclick="backItemIndex();" style="float: right;margin-right: 10px;text-decoration: underline;color: blue;cursor: pointer;">Đóng</div>
            <div style="clear: both;"></div>
        </div>

    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid" style="margin-top: 10px;">
        <div class="span4">&nbsp;</div>

        <div class="span12">
            <?php echo $this->form($this, $this->form, 1, $echo_form_tag = FALSE); ?>
        </div>

    </div>

    <div class="row-fluid" style="margin-top: 10px;">



        <?php
        if (is_numeric($this->form->getElement('id')->getValue())) {
            $mapper = new Default_Model_Answer();
            $menus = $mapper->select('*')->where("question_id=" . $this->form->getElement('id')->getValue())->order('sign')->fetchAll();
            $dap_an = isset($this->dap_an) ? $this->dap_an : Core_Db_Table::getDefaultAdapter()->query('select answer_id from dap_an where question_id=' . $this->form->getElement('id')->getValue())->fetchColumn();
            if (is_array($menus) && count($menus) > 0) {
                ?>
                <h3 style="text-align: center;">Chọn đáp án</h3>

                <?php
                foreach ($menus as $menu) {
                    ?>
                    <div>

                        <label>

                            <input type="radio" name="dap_an" value="<?php echo $menu['id']; ?>"<?php if ($dap_an == $menu['id']) { ?> checked<?php } ?>/>
                            <?php
                            echo $menu['sign'] . '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' . $menu['content'];
                            ?>
                        </label>

                    </div>    
                    <?php
                }
                ?>

                <?php
            }
        }
        ?>
    </div>    

    <div class="row-fluid" style="margin-top: 10px;">



        <?php
        if ($this->form->getElement('question_id') == null) {
            $mapper = new Default_Model_Index();
            $menus = $mapper->getMatHangs($only_parent = FALSE);
            $rows=Core_Db_Table::getDefaultAdapter()->query("select * from nganhnghe_question where question_id='" . $this->form->getElement('id')->getValue()."'")->fetchAll();
            $nganhnghe_ids=array();
            if(is_array($rows)&&count($rows)>0){
                foreach ($rows as $row){
                    $nganhnghe_ids[]=$row['nganhnghe_id'];
                }
            }
            if (is_array($menus) && count($menus) > 0) {
                ?>
                <h3 style="text-align: center;">Chọn ngành nghề</h3>

                <?php
                foreach ($menus as $menu) {?>
                    <div style="margin-left: 50px;">

                            <label>

                                <input type="checkbox" name="nganhnghe_id[]" value="<?php echo $menu['id']; ?>"<?php if (in_array($menu['id'], $nganhnghe_ids)) { ?> checked<?php } ?>/>
                                <?php
                                echo $menu['title'];
                                ?>
                            </label>

                        </div>    
                
               

                <?php
                }
            }
        }
        ?>
    </div>    


</form>    

<script type="text/javascript">
    jQuery(function ($) {
       

        $("form").find("textarea").eq(0).focus();

    });

</script>



