<style>
    .row0{
        background-color: white;

    }
    .row1{
        background-color: silver;

    }

    img.answer.delete{
        width: 16px;
        height: 16px;
    }
    img.question.delete{
        width: 32px;
        height: 32px;
    }

    img.answer.edit{
        width: 24px;
        height: 24px;
    }
    img.question.edit{
        width: 48px;
        height: 48px;
    }
    div.icon-down{
        background-image: url('<?php echo $this->baseUrl(); ?>/images/down.png');
    }

</style>
<?php
$items = $this->items;



$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
}
Zend_Loader::loadFile('Numeric.php', "./../library/Core/Common/", true);
Zend_Loader::loadFile('String.php', "./../library/Core/Common/", true);
?>
<script type="text/javascript">


    function addItem() {
        window.location = "<?php echo $this->baseUrl('/admin/question/add/'); ?>";

    }
    function editItem(img) {
        jQuery("form#edit-form").find('input[type="hidden"]').eq(0).val(jQuery(img).parent().parent().attr("id")).attr("name", "id");
        jQuery("form#edit-form").submit();

    }
jQuery(function ($) {
        $(".parent").click(function () {
            if($(this).attr('src').indexOf('down')!=-1){
                src=$(this).attr('src');                
                src=src.replace('down','up');  
            }
            else{
                src=src.replace('up','down');
            }
            
            $(this).attr('src',src);
            $(this).parent().parent().next().slideToggle();
        });
    });

</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="padding-top:20px;">
    
    <div class="span12">
        <table width="100%" style="-moz-border-radius: 10px 10px 10px 10px;background: #D0E3F5;">
            <tr>
                <td width="80%" align="center" style="float: left;text-align: center;font-size: 20px;color: yellow;"><?php if (isset($ten_loai_mat_hang)) echo $ten_loai_mat_hang; ?></td>

                <td onclick="addItem();" onmouseover="this.style.cursor = 'pointer';" style="text-decoration: underline;color: blue;" width="20%" align="right">Thêm câu hỏi</td>

            </tr>
        </table>
    </div>
</div>

<div class="row-fluid">
    
        <?php
        $row = 0;
        foreach ($items as $item) {


            if ($row == 0) {
                $row = 1;
            } else {
                $row = 0;
            }



            $item_des = $item['content'];
            ?>

            <div class="row-fluid row<?php echo $row; ?>" id="<?php echo $item['id']; ?>">
                <div class="span1" title="Thêm mới câu trả lời">
                    <a href="<?php echo $this->baseUrl('/admin/question/addanswer/question_id/') . $item['id']; ?>">
                        <img style="width: 43px;height: 41px;" src="<?php echo $this->baseUrl("/images/icon/add.gif"); ?>"/>
                    </a>
                </div>
                <div class="span8">
    <?php echo $item_des; ?>
                </div>
                <div class="span2">
                    <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->baseUrl('/admin/question/delete/question_id/') . $item['id']; ?>">
                        <img class="delete question" src="<?php echo $this->baseUrl("/images/icon/delete-icon.png"); ?>"/>                                                   
                    </a>

                    <a href="<?php echo $this->baseUrl('/admin/question/edit/id/') . $item['id']; ?>">
                        <img class="edit question" title="Click vào đây để sửa" style="cursor: pointer;" src="<?php echo $this->baseUrl("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                    </a>
                </div>
                <div class="span1" style="margin: 0 auto;text-align: center;display: table-cell;vertical-align: middle;">
                    <?php 
                    if(count($item['answers'])>0){ ?>
                    <img class="parent" src="<?php echo $this->baseUrl(); ?>/images/down.png" style="width: 32px;height: 32px;cursor: pointer;"/>
                    <?php 
                    }
                    ?>
                </div>
            </div>
    
    <div class="row-fluid" style="display: none;background-color: blue;color: white;">
            
                <?php
                $answers = $item['answers'];
                foreach ($answers as $answer) {
                    $item_des = $answer['content'];
                    
                    ?>
        <div class="row-fluid" style="border-bottom: dotted black 1px;border-right: solid 1px black;">
                        <div class="span1">

                        </div>
                        <div class="span1" style="border-right: solid 1px black;">
                            <?php echo $answer['sign']; ?>
                        </div>
                        <div class="span8" style="border-right: solid 1px black;">
        <?php echo $item_des; ?>
                        </div>
                        <div class="span2" style="border-right: solid 1px black;">
                            <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->baseUrl('/admin/question/delete/answer_id/') . $answer['id']; ?>">
                                <img class="delete answer" src="<?php echo $this->baseUrl("/images/icon/delete-icon.png"); ?>"/>                                                   
                            </a>

                            <a href="<?php echo $this->baseUrl('/admin/question/editanswer/id/') . $answer['id']; ?>">
                                <img class="edit answer" title="Click vào đây để sửa" style="cursor: pointer;" src="<?php echo $this->baseUrl("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                            </a>
                        </div>
                        
                        </div>
                        <?php
                    }
                    ?>
                
            </div>


            <?php
        }
        ?>
    
</div>
<form method="post" action="<?php echo $this->url(); ?>">
    <div class="row-fluid">
        <div class="span12">
<?php if ($this->total > $this->limit) { ?>
                <table style="width: 100%;">
                    <tfoot>
                        <tr>
                            <td colspan="3" style="width: 100%;"><?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?></td>
                        </tr>
                    </tfoot>
                </table>
                <?php
            }
            ?>
        </div>
    </div>
</form>

