<script type="text/javascript">
    jQuery(function () {
        jQuery("#username").focus();
    });
    function validate(form, username, password) {
        username.value = trimEnd(username.value);
        username.value = trimStart(username.value);
        if (username.value == null || username.value == "") {
            username.setAttribute('style', "border-color: red;");
            username.focus();
            return false;
        }
        if (username.value.indexOf(" ", 0) != -1) {
            username.setAttribute('style', "border-color: red;");
            username.focus();
            return false;
        }
        if (password.value == null || password.value == "") {
            password.setAttribute('style', "border-color: red;");
            password.focus();
            return false;
        }
        if (password.value.indexOf(" ", 0) != -1) {
            password.setAttribute('style', "border-color: red;");
            password.focus();
            return false;
        }
        return true;
    }
    function trimEnd(s) {
        if (s == null || s == "")
            return s;
        hasChar = false;
        j = s.length - 1;
        for (i = s.length - 1; i > - 1; i--)
            if (s.charAt(i) != ' ') {
                j = i;
                hasChar = true;
                break;
            }
        if (!hasChar)
            return "";
        temp = "";
        for (i = 0; i <= j; i++)
            temp += s.charAt(i);
        return temp;
    }
    function trimStart(s) {
        if (s == null || s == "")
            return s;
        hasChar = false;
        j = 0;
        for (i = 0; i < s.length; i++)
            if (s.charAt(i) != ' ') {
                j = i;
                hasChar = true;
                break;
            }
        if (!hasChar)
            return "";
        temp = "";
        for (i = j; i < s.length; i++)
            temp += s.charAt(i);
        return temp;
    }

</script>
<div class="row-fluid" style="height: 100px;margin-top: 50px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <?php 
        if(isset($this->loginResult)){
            echo 'Thông tin đăng nhập không đúng. Vui lòng nhập lại.';
        }
        ?>
    </div>
    <div class="span3">&nbsp;</div>
</div>
<div class="row-fluid">
    <div class="span2">&nbsp;</div>
    <div class="span8">
        <form action="<?php echo $this->baseUrl('/default/index/login'); ?>" method="post" onsubmit="return validate(this, this.username, this.password);">
            <table width="40%" class="tblogin">
                
                <tr>
                    <td><label for="firstname">email:</label></td> <td ><input id="username" name="username" type="text" /></td>
                </tr>
                <tr>
                    <td><label for="firstname">password:</label></td> <td><input name="password" type="password"/></td>
                </tr>    
                <tr>
                    <td> </td><td > <input type="submit" id="btnLogin" class="btn" value="Log in"  /></td>
                </tr>
            </table>
        </form>
    </div>
    <div class="span2">&nbsp;</div>
</div>


