<script type="text/javascript">
function save(){	
	document.form1.submit(); 
}
</script>
<?php
$message=$this->message;
if($message!=""){
?>
<div class="row-fluid" style="margin-top: 20px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='color: red;'>
        <?php
        echo $message;
        ?>
    </div>
    <div class="span3">&nbsp;</div>
</div>
<?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
	  <div style="float: left;"></div>
	  <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
	  <div style="clear: both;"></div>
	</div>
        
    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form1" id="form1" action="<?php echo $this->url();?>" method="post">
<div class="row-fluid">
    <div class="span12" style="padding-top: 20px;">
        <table border="1" style="width: 100%">
            <thead>
                <tr>
                    <th>Tiếng Việt</th>
                    <th>Tiếng Trung</th>
                    <th>Tiếng Anh</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $data=$this->data;
                $dynamic=$this->dynamic;                
                ?>
                <tr>
                    <td>
                        <input type="text" name="text_vi" value="<?php echo $data["text_vi"];?>">
                        
                    </td>
                    <td>
                        <input type="text" name="text_cn" value="<?php echo $data["text_cn"];?>">
                    </td>
                    <td>
                        <input type="text" name="text_en" value="<?php echo $data["text_en"];?>">
                    </td>
                </tr>
            
                
            </tbody>
        </table>
    </div>
</div>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span4">&nbsp;</div>
                <div class="span2">
                    <div class="row-fluid">
                        <div class="span3">
                            <input type="radio" value="1" name="dynamic" id="dynamic"<?php if($dynamic=='1') echo ' checked';?>/>
                        </div>
                        <div class="span9">
                            <label for="dynamic">Chuyển động</label>
                        </div>
                        
                
                    </div>
                
                </div>
                <div class="span6">
                    <div class="row-fluid">
                        <div class="span1">
                            <input type="radio" value="0" name="dynamic" id="static"<?php if($dynamic=='0') echo ' checked';?>/>
                        </div>
                        <div class="span11">
                            <label for="static">Đứng yên</label>
                        </div>
                        
                
                    </div>
                
            </div>
                </div>
</form>
