<?php
echo $this->doctype();
?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8;" />
<?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-2.0.3.js"></script>
        <!--bootstrap-->
        <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" type="text/css"/> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.js"></script>        
        <!--end bootstrap-->
        <!--menu-->
        <link href="<?php echo $this->baseUrl('/css/menu/menu.css'); ?>" media="screen" rel="stylesheet" type="text/css" />				 
        <!--end menu-->             
        <!-- top bottom-->
        <link href="<?php echo $this->baseUrl(); ?>/css/top_bottom.css" rel="stylesheet" type="text/css"/>
        <!-- end top bottom-->
        <link href="<?php echo $this->baseUrl(); ?>/css/phan_trang.css" rel="stylesheet" type="text/css"/> 
        <!--layout-->
        <link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css"/>
        <!--end layout--> 

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/jquery.cluetip.css" media="all" />
        <!--search-->
        <link href="<?php echo $this->baseUrl(); ?>/css/form_search/search.css" rel="stylesheet" type="text/css"/>
        <!--end search--> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.textarea-expander.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.cluetip.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>          
        <!--progress load page-->
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/page_loader/jquery.queryloader2.js'); ?>"></script>
        <!--end progress load page-->
        
       
        
          
        <!-- append form for click in index page-->
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/build_form_click.js"></script>
        <!-- end append form for click in index page-->
        
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.dropotron.min.js"></script>


        <script type="text/javascript">
            /**
             * index.phtml             
             */
            $(window).scroll(function() {
                if ($(this).scrollTop() > 100) {
                    $("#gotop").removeAttr("href");
                    $("#gotop").stop().animate({
                        bottom: "0",
                        right: "0"
                    }, {
                        duration: 800,
                        queue: false
                    })
                } else {
                    $("#gotop").stop().animate({
                        bottom: "-50",
                        right: "-50"
                    }, {
                        duration: 1000,
                        queue: false
                    })
                }
                if ($(this).scrollTop() > 100) {
                    $("#gobottom").removeAttr("href");
                    $("#gobottom").stop().animate({
                        top: "-50",
                        right: "-50"
                    }, {
                        duration: 800,
                        queue: false
                    })
                } else {
                    $("#gobottom").stop().animate({
                        top: "0",
                        right: "0"
                    }, {
                        duration: 1000,
                        queue: false
                    })
                }

            });
            /**
             * end index.phtml
             **/
            jQuery(function($) {
                /**
                 * index.phtml
                 **/
                $("body").queryLoader2({
                    barColor: "#6e6d73",
                    backgroundColor: "#fff1b0",
                    percentage: true,
                    barHeight: 5,
                    completeAnimation: "grow",
                    minimumTime: 100
                });
                $("#gotop").click(function() {
                    $("html, body").animate({
                        scrollTop: 0
                    }, "slow");
                    return false
                })
                $("#gobottom").click(function() {
                    $("html, body").animate({
                        scrollTop: $('#footer').offset().top
                    }, 970);
                    return false
                })
                /**
                 * end index.phtml
                 **/            
                
                

            });

        </script>
        <style>

            /**
             * danh sách mặt hàng
             */            
            table.mat_hang_list td div:only-child{
                border-style: dotted;
                border-width: 1px;
                margin: 5px;
                border-radius: 7px 7px 7px 7px;
            }            
            /**
             * end danh sách mặt hàng
             */      
        </style>

    </head>
    <body style="background:black;">
        <div style="display: none;" id="dialog-modal-mathang" title="Chi tiết mặt hàng">    
        </div>
        <div class="container">
            <!--header-->

            <div class="container" style="padding-top: 30px;background: #525252;height: 100px;">
                <div class="row-fluid">
                    <div class="span3">
<?php
Zend_Loader::loadFile('./../library/Core/Common/Image.php', null, true);
Image::echoImage($this->baseUrl('/images/dien_luc.jpg'), 70, 70, 'height', array('id' => 'logo-img'));
?>
                        

                    </div>
                    <div class="span5">
                        <div class="row-fluid" style="font-size: 30px;line-height: 1.3;text-align: center;color: #c1976c;font-family: serif;padding-top: 35px;">
                            <div class="span12">Điện lực</div>
                        </div>  
                    </div>
                    <div class="span4">
                        <?php
					          $auth = Zend_Auth::getInstance();
						      if($auth->hasIdentity())
						      {
						          $identity=$auth->getIdentity();
						          echo '<div style="float: right;margin-right: 10px;"><a style="color: white;" href="'.$this->baseUrl('/admin/index/logout').'">Thoát</a></div>';
						          
						          
						      }				           
					          ?>
                    </div>


                    
                </div>
                

            </div>            
            <!--end header-->
            <!--middle-->
            <!--above-->                           
            <div class="row-fluid" style="margin-top: 10px;">

                <div class="span1">&nbsp;</div>
                <div class="span6">
                        <ul id="topnav">

                            <li><a href="/admin/nganhnghe">Ngành nghề</a></li>
                            <li><a href="/admin/question">Ngân hàng câu hỏi</a></li>
                            <li><a href="/admin/user">User</a></li>
<!--                            <li>
                                <a>Nội dung phía trên</a>
                                <span>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/language">Ngôn ngữ</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/menu">Menu</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/logo">Logo</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/header">Header text</a></div>
                                </span>
                            </li>
                            <li>
                                <a>Nội dung phía dưới</a>
                                <span>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/lienhe">Liên hệ</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/slide">Slide</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/resource">Giới thiệu(con người)</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/us">Giới thiệu(giá trị của chúng tôi)</a></div>
                                    <div><a href="<?php echo $this->baseUrl();?>/admin/news">Giới thiệu(tin tức)</a></div>
                                </span>
                            </li>-->
                               

                        </ul>
                   </div>
                


            </div>
            <!--end above-->
            <!--below-->    
            <div class="row-fluid" style="margin-top: 10px;background: white;">

                <div class="span1">&nbsp;</div>
                <div class="span10" style="min-height: 600px;">
                    
<?php echo $this->layout()->content; ?>           
                    
                </div>
                <div class="span1">&nbsp;</div>
            </div>

            <!--end below--> 
            <!--end middle-->
            <!--footer-->            
            <div class="row-fluid" align="center" style="background:black;color:white;">	
                <div class="span12">
<?php //echo $this->footer(array('Shop áo quần 236', 'Địa chỉ: 146 Lê Duẩn - Đà Nẵng (vào 20m) Số điện thoại: 0919.319.827 - 0917.987.627 - 05113818071 (Gặp chị Tâm)')); ?>
                </div>
            </div>
            <!--end footer-->

        </div>
        <a id="gotop" style="bottom: -50px; right: -50px;"></a>
        <a id="gobottom" style="top: 0px; right: 0px;"></a>
        <div id='footer'/>
    </body>