<?php
echo $this->doctype();

$module_name = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
if ($module_name == 'default') {
    $language = 'vi';
} else if ($module_name == 'en') {
    $language = 'en';
} else if ($module_name == 'cn') {
    $language = 'cn';
}
$controller_name = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action_name = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$params=Zend_Controller_Front::getInstance()->getRequest()->getParams();
$params_string='';
if(is_array($params)&&count($params)>0){
    foreach ($params as $key => $value) {
        if ($key != "module" && $key != "controller" && $key != "action") {
            $params_string.="$key/$value/";
        }
    }
}
$url_after_moudule="$controller_name/$action_name/$params_string";
if($action_name=="search"){
    $url_after_moudule="";
}
$table = Core_Db_Table::getDefaultAdapter();
$row_language = $table->select("text_$language")->from("language")->order("order")->query()->fetchAll();
$menu_items = $table->select("*")->from("menu")->where("parent_id is null and active=1")->order("order")->query()->fetchAll();
$header_text = $table->select("text_$language")->from("header_text")->query()->fetchAll();
$header_text=$header_text[0]["text_$language"];

$data = array();
$db = Zend_Db_Table::getDefaultAdapter();
$db->setFetchMode(Zend_Db::FETCH_ASSOC);
$logo = $db->fetchRow("select * from logo");
$header_text_dynamic = $db->fetchRow("select * from header_text_dynamic");
$slide_texts=$db->fetchAll("select * from slide_text");
$san_pham_parent=$db->fetchAll("select * from mat_hang where parent_id is null");
if($controller_name=="index"&&$action_name!="search"){
    $content_background_image="qiy7n8diA.jpg";    
}
else{
    if(false){
        $content_background_image="bg_content_top_home_2_ie8.png"; 
    }
    else{
        $content_background_image="bg_content_top_home_2.png"; 
    }
       
}
?>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8;" />
<?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.9.1.min.js"></script>
        <!--bootstrap-->
        <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl(); ?>/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" type="text/css"/> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.js"></script>        
        <!--end bootstrap-->
        <!--menu-->
        <link href="<?php echo $this->baseUrl('/css/menu/menu.css'); ?>" media="screen" rel="stylesheet" type="text/css" />				 
        <!--end menu-->             
        <!-- top bottom-->
        <link href="<?php echo $this->baseUrl(); ?>/css/top_bottom.css" rel="stylesheet" type="text/css"/>
        <!-- end top bottom-->
        <!--phân trang-->
        <link href="<?php echo $this->baseUrl(); ?>/css/phan_trang.css" rel="stylesheet" type="text/css"/>
        <!--end phân trang--> 
        <!--layout-->
        <link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet" type="text/css"/>
        <!--end layout--> 
        <!--sản phẩm-->
        <link href="<?php echo $this->baseUrl(); ?>/css/product/product.css" rel="stylesheet" type="text/css"/>
        <!--end sản phẩm-->         

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/jquery-ui-1.10.3/themes/smoothness/jquery-ui.css'); ?>" type="text/css"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/jquery.cluetip.css" media="all" />
        <!--search-->
        <link href="<?php echo $this->baseUrl(); ?>/css/form_search/search.css" rel="stylesheet" type="text/css"/>
        <!--end search--> 
        <!--slide text-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/slide_text/presentationCycle.css" media="all" />                       
        <!--end slide text-->
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/jquery-ui-1.10.3/ui/jquery-ui.js"></script>          
        <!--progress load page-->
        <?php
        if (!strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) { ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/page_loader/jquery.queryloader2.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/page_loader/jquery.queryloader2.exe.js'); ?>"></script>
        <?php }?>
        <!--end progress load page-->
        <!--slide text-->        
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/slide_text/jquery.cycle.all.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/slide_text/presentationCycle.js'); ?>"></script>
        <!--end slide text-->
        <!--hiệu ứng chuyển động ảnh-->
        <?php
        if($logo['dynamic']=="1"){
        ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.cycle.all.js'); ?>"></script>
        <?php
        }
        ?>
        <!--end hiệu ứng chuyển động ảnh-->
        <!--chạy chữ-->
        <?php
        if($header_text_dynamic['dynamic']=="1"){
        ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/animation_text/textTyper.js'); ?>"></script>
        <?php
        }
        ?>
        <!--end chạy chữ-->        
        
        <!--start slide ảnh-->
        <?php
        //if (!strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) { ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery.carouFredSel-6.2.1-packed.js'); ?>"></script>
        <?php
        //} ?>
        
        <!--end slide ảnh-->
        <?php
        if(false){?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/lib_radius/jquery.corner.js'); ?>"></script>
        <?php }?>


        <script type="text/javascript">
            /**
             * index.phtml             
             */
            $(window).scroll(function() {
                
                if ($(this).scrollTop() > 100) {
                    $("#gotop").removeAttr("href");
                    $("#gotop").stop().animate({
                        bottom: "0",
                        right: "0"
                    }, {
                        duration: 800,
                        queue: false
                    })
                } else {
                    $("#gotop").stop().animate({
                        bottom: "-50",
                        right: "-50"
                    }, {
                        duration: 1000,
                        queue: false
                    })
                }
                if ($(this).scrollTop() > 100) {
                    $("#gobottom").removeAttr("href");
                    $("#gobottom").stop().animate({
                        top: "-50",
                        right: "-50"
                    }, {
                        duration: 800,
                        queue: false
                    })
                } else {
                    $("#gobottom").stop().animate({
                        top: "0",
                        right: "0"
                    }, {
                        duration: 1000,
                        queue: false
                    })
                }

            });
            /**
             * end index.phtml
             **/                       
            
            jQuery(function($) { 
                
                    
                
                $( "form#form_search input[type='text']" ).autocomplete({                      
                      source: function( request, response ) {
                        $.ajax({
                          url:"<?php echo $this->baseUrl()."/$module_name";?>/index/autocomplete/",
                          dataType: "json",
                          data: {                            
                            max_rows: 10,
                            q: request.term
                          },
                          success: function( data ) {
                              
                            response( $.map( data, function( item ) {
                              return {                                
                                label: item.ten_mat_hang_<?php echo $language;?>
                                //value: item.ten_mat_hang
                              }
                            }));
                          }
                        });
                      },
                      minLength: 1,
                      open: function() {
                        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
                      },
                      close: function() {
                        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
                      }
                });
                lis=$("ul#topnav li");
                for(i=0,n=lis.length;i<n;i++){
                    span=$(lis[i]).find("span");
                    if(span.length>0){
                        $(lis[i]).find("a").eq(0).removeAttr("href").css("cursor","pointer");
                        $(lis[i]).click(function (){
                            $(lis[i]).find("span").eq(0).show();
                        });
                    }
                }
                
                $("div#logo_header img").css("cursor","pointer").click(function (){
                    
                    <?php
                    if($language=='vi'){
                        echo 'window.location="'.$this->baseUrl("/").'";';
                    }
                    else if($language=="cn"){
                        echo 'window.location="'.$this->baseUrl("/cn").'";';
                    }
                    else if($language=="en"){
                        echo 'window.location="'.$this->baseUrl("/en").'";';
                    }
                    ?>
                });
                presentationCycle.init();
//                $("a.p_c_i_img").corner("round 150px");
                
                /**
                 * slide                 
                 */
                <?php
        //if (!strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) { ?>
                $('#foo0').carouFredSel({
//                    items               : 1,
prev: {
       button  : "#msprev"
},
next: {
       button  : "#msnext"
},
                    scroll: { items:1,duration: 2000}
//                    auto: {
//                        pauseOnHover: 'resume',
//                        progress: '#timer1'
//                    }
                }, {
                    transition: true                    
                });
                <?php
        //} ?>
                /**
                 * end slide                 
                 */
                /**
                 * index.phtml
                 **/
               
                $("#gotop").click(function() {
                    $("html, body").animate({
                        scrollTop: 0
                    }, "slow");
                    return false
                })
                $("#gobottom").click(function() {
                    $("html, body").animate({
                        scrollTop: $('#footer').offset().top
                    }, 970);
                    return false
                })
                /**
                 * end index.phtml
                 **/            
                
                /**                 
                 * header.phtml
                 **/
                <?php
                if($logo['dynamic']=="1"){
                ?>
                $('#logo_header').cycle({
                    fx: 'zoom', sync: false, delay: -2000
                });
                <?php
                }
                ?>
                <?php
                if($header_text_dynamic['dynamic']=="1"){
                ?>
                $('div#simpleDiv').textTyper({repeatAnimation: true, repeatTimes: 100, speed: 50});
                <?php
                }
                ?>
                
                


                /**
                 * end header.phtmls                         
                 **/
                

            });

        </script>
        <style>
            body{
background-image: url(<?php echo $this->baseUrl(); ?>/images/background/1820590.jpg);
background-size: 4000px 2500px;
            }
            <?php
        //if (!strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) { ?>
            .list_carousel ul {
                text-align: center;
                list-style: none;
                display: block;
                margin:0px;
                padding: 0px;
            }
            .list_carousel li {
                margin:0px;
                padding: 0px;
/*                width: 970px;                */
                height:370px;
                display: block;
                float: left;
                margin-right:5px;
            }
            
            <?php
        //} ?>
            
            
            
            
            
            

        </style>

    </head>
    <body>
        <div class="container" style="width:1170px;">
            <!--header-->

            <div class="container" style="padding-top: 30px;width:1170px;">
                <?php if(false){?>
                <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/8684100-beautiful-abstract-lotus-background_ie8.jpg);min-height: 100px;height:115px;">
                <?php }
                else{
                ?>                    
                <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/8684100-beautiful-abstract-lotus-background.jpg);background-size: 50px 36px;min-height: 100px;height:115px;">
                <?php }?>
                    <div class="span3">
                        <div class="row-fluid" style="padding-top: 10px;padding-left: 10px;">
                            <?php
                            if($logo['dynamic']=="1"){
                                ?>
                            
                            <div class="span12" id="logo_header">
                                <?php
                                Zend_Loader::loadFile('./../library/Core/Common/Image.php', null, true);
                                Image::echoImage($this->baseUrl($logo['file_name']), 100, 100, 'height', array('id' => 'logo-img'));
                                Image::echoImage($this->baseUrl($logo['file_name']), 100, 100, 'height', array('id' => 'logo-img1'));
                                ?>
                            </div>
                            <?php
                            }
                            else{
                                ?>
                            <div class="span12" id="logo_header">
                                <?php
                                Zend_Loader::loadFile('./../library/Core/Common/Image.php', null, true);
                                Image::echoImage($this->baseUrl($logo['file_name']), 100, 100, 'height', array('id' => 'logo-img'));                           
                                ?>
                            </div>
                            <?php
                            }
                            ?>
                        </div>  
                    </div>
                    <div class="span5">
                        <?php
                        if(true){?>
                        <div class="row-fluid" <?php if($header_text_dynamic['dynamic']=="1") echo ' id="simpleDiv"';?> style="font-size: 30px;line-height: 1.3;text-align: center;color: #c1976c;padding-top: 35px;font-family: Lucida Calligraphy Italic,serif, Helvetica, Arial, sans-serif;">
                        <?php    
                        }
                        else{
                        ?>
                        <div class="row-fluid" <?php if($header_text_dynamic['dynamic']=="1") echo ' id="simpleDiv"';?> style="font-size: 30px;line-height: 1.3;text-align: center;color: #c1976c;padding-top: 35px;font-family: fontForHeader,serif, Helvetica, Arial, sans-serif;">
                        <?php
                        }
                        ?>
                            <div class="span12"><?php echo $header_text;?></div>
                        </div>                        
                    </div>

                    <div class="span4" style="padding-left: 20px;padding-top: 30px;">
                        <a class="view_more" href="<?php echo $this->baseUrl('/'.$url_after_moudule); ?>">
<?php
echo $row_language[0]["text_$language"];
?>
                            </a>
                        
                        
                            <a class="view_more" href="<?php echo $this->baseUrl('/cn/'.$url_after_moudule); ?>">
<?php
echo $row_language[1]["text_$language"];
?>
                            </a>
                        
                            <a class="view_more" href="<?php echo $this->baseUrl('/en/'.$url_after_moudule); ?>">
<?php
echo $row_language[2]["text_$language"];
?>
                            </a>
                        
                        

                    </div>

<!--                    <div class="span5" style="padding-left: 20px;padding-top: 10px;">
                        <div class="language english">
                            <a href="<?php echo $this->baseUrl('/en/'.$url_after_moudule); ?>">
<?php
echo $row_language[2]["text_$language"];
?>
                            </a>
                        </div>
                        <div class="language chinese">
                            <a href="<?php echo $this->baseUrl('/cn/'.$url_after_moudule); ?>">
<?php
echo $row_language[1]["text_$language"];
?>
                            </a>
                        </div>
                        <div class="language vietnamese">
                            <a href="<?php echo $this->baseUrl('/'.$url_after_moudule); ?>">
<?php
echo $row_language[0]["text_$language"];
?>
                            </a>
                        </div>
                        <div style="clear: both;"></div>
                        

                    </div>-->
                </div>
                

            </div>            
            <!--end header-->
            <!--middle-->
            <!--above-->   
            <?php if(false){?>
            <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/bg_ie8.jpg);min-height: 70px;height: 70px;padding-top: 20px;">
            <?php }
            else{
            ?>      
            <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/bg.jpg);background-size: 20px 31px;min-height: 70px;height: 70px;padding-top: 20px;">
            <?php }?>
                <div class="span1">&nbsp;</div>
                <div class="span6" style="min-width: 500px;">
                    <ul id="topnav">

                        <?php
                        for($i=0,$n=count($menu_items);$i<$n;$i++){
                            $link='';                                
                            if($language=='vi'){
                                $link.='/default';
                            }
                            else if($language=='cn'){
                                $link.='/cn';
                            }
                            else if($language=='en'){
                                $link.='/en';
                            }
                            $link.=$menu_items[$i]['link'];
                            echo '<li>';
                            echo '<a href="'.$this->baseUrl().$link.'">'.$menu_items[$i]["text_$language"].'</a>';
                            if($menu_items[$i]['is_product']=='1'){
                                echo '<span>';
                                foreach ($san_pham_parent as $san_pham){
                                    if($language!="vi"){
                                        echo '<div><a href="'.$this->baseUrl().'/'.$language.'/index/detail/id/'.$san_pham['id'].'">'.$san_pham["title_$language"].'</a></div>';
                                    }
                                    else{
                                        echo '<div><a href="'.$this->baseUrl().'/index/detail/id/'.$san_pham['id'].'">'.$san_pham["title_$language"].'</a></div>';
                                    }
                                    
                                }
                                echo '</span>';
                            }
                            else{
                                $temps=$db->fetchAll("select * from menu where active=1 and parent_id=".$menu_items[$i]['id']);
                                if(is_array($temps)&&count($temps)>0){
                                    echo '<span>';
                                    foreach ($temps as $temp_menu){
                                        $link1='';                                
                                        if($language=='vi'){
                                            $link1.='/default';
                                        }
                                        else if($language=='cn'){
                                            $link1.='/cn';
                                        }
                                        else if($language=='en'){
                                            $link1.='/en';
                                        }
                                        $link1.=$temp_menu['link'];
                                        echo '<div><a href="'.$this->baseUrl().$link1.'">'.$temp_menu["text_$language"].'</a></div>';
                                    }
                                    echo '</span>';
                                }
                            }
                            
                            echo '</li>';

                            
                        }
                        ?>       

                    </ul>


                </div>

                
                <div style="float: right;width:200px;">               
                            <form id="form_search" action="<?php echo $this->baseUrl("/$module_name/index/search");?>" method="post">
                                <input type="text" name="search_text" value="" style="margin-top: 10px;margin-right: 0px;border: 1px solid #786e6a;height: 18px;line-height: 18px;padding: 0 5px;background: #544741;color: #f8f0e6;width: 120px;"/>
                                <img onclick="jQuery(this).parent().submit();" style="width: 20px;height: 20px;margin-left: 0px;cursor: pointer;" src="<?php echo $this->baseUrl("/images/icon/search.png");?>"/>

                            </form>
                </div>


            </div>
            <!--end above-->
            <!--below-->
            <?php if(false){?>
            <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/bg_content_top_home_11_ie8.png);">
            <?php }
            else{
            ?>  
            <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/background/bg_content_top_home_11.png);background-size: 1170px 660px;">
            <?php }?>
                <div class="span12">
                    <div class="row-fluid">                
                        <div class="span12" style="height:370px;">

                            <div class="span2" style="text-align: center;vertical-align: middle;">
                                <img id="msprev" src="<?php echo $this->baseUrl("/images/icon/arrow_left.png");?>" style="cursor: pointer;margin-top: 150px;width: 45px;height: 45px;"/>                                
                            </div>
                            <div class="list_carousel span8">
                                <ul id="foo0">
                                    <?php
                                    if (is_array($san_pham_parent) && count($san_pham_parent) > 0) {
                                        foreach ($san_pham_parent as $file) {
                                            echo '<li>';
                                            if (!strstr($_SERVER['HTTP_USER_AGENT'], "MSIE")) {
                                                echo '<img style="height:370px;width:370px;" src="' . $this->baseUrl() . $file['logo'] . '" alt=""/>';
                                            }
                                            else{
                                                echo '<img style="height:370px;" src="' . $this->baseUrl() . $file['logo'] . '" alt=""/>';
                                            }
                                            
                                            echo '</li>';
                                        }
                                    }
                                    ?>

                                </ul>
                                <div id="timer1" class="timer"></div>
                            </div>
                            <div class="span2" style="text-align: center;vertical-align: middle;">
                                <img id="msnext" src="<?php echo $this->baseUrl("/images/icon/arrow_right.png");?>" style="cursor: pointer;width: 45px;height: 45px;margin-top: 150px;"/>                                
                            </div>


                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">&nbsp;</div>
                    </div>
                    <div class="row-fluid">
                        <div style="color:white;" class="pc_container" id="presentation_container">

                            <?php
                            if (is_array($slide_texts) && count($slide_texts) > 0) {

                                for ($i = 0, $n = count($slide_texts); $i < $n; $i++) {
                                    $slide_text = $slide_texts[$i];
                                    ?>
                                    <div class="pc_item">
                                        <div class="desc">
                                            <div class="row-fluid">
                                                <div class="span12" style="text-align: center;text-transform: uppercase;padding-top: 20px;">
                                                    <?php echo $slide_text["title_$language"]; ?>
                                                </div>
                                            </div>
                                            <div class="row-fluid">
                                                <div class="span12">&nbsp;</div>
                                            </div>
                                            <div class="row-fluid">
                                                <div class="span1">&nbsp;</div>
                                                <div class="span10" style="max-height: 150px;">
                                                    <?php echo nl2br($slide_text["mo_ta_$language"]); ?>
                                                </div>
                                                <div class="span1">&nbsp;</div>
                                            </div>
                                        </div>
                                    </div>

                                    <?php
                                }
                            }
                            ?>

                        </div>                    
                    </div>
                </div>
            </div>            
            

            <div class="row-fluid" style="background-image: url(<?php echo $this->baseUrl("/images/background/$content_background_image"); ?>);<?php if($content_background_image=="bg_content_top_home_2.png") echo ' background-size: 1170px 1000px;';?>">

                
                <div class="span12" style="min-height: 600px;">
                    <div class="row-fluid"><div class="span12">&nbsp;</div></div>
<?php echo $this->layout()->content; ?>           
                </div>
            </div>

            <!--end below--> 
            <!--end middle-->
            
            
            
            

        </div>
        <a id="gotop" style="bottom: -50px; right: -50px;"></a>
        <a id="gobottom" style="top: 0px; right: 0px;"></a>
        <div id='footer'></div>
        <!--footer-->   
        
        
        <div class="container" style="min-width: 1170px;<?php if(false) echo 'width: 1170px;';?>background-image: url(<?php echo $this->baseUrl("/images/background/bg_content_top_home_1.png"); ?>);background-size: 1170px 100px;">        
            <div class="row-fluid" align="center" style="color:white;">	
                <div class="span12">
                    <hr/>
                     Copyright &copy; 2014 VietAgar Co. Ltd. - All rights reserved
                </div>
            </div>
        </div>        
        <!--end footer-->
    </body>
    
    