<?php 
Zend_Loader::loadFile('./../library/Core/Common/Image.php',null,true);
Zend_Loader::loadFile('String.php',"./../library/Core/Common/",true);   
$matHangs=$this->matHangs;
$language=$this->language;
if($language=="vi"){
    $language_module_url="";
}
else{
    $language_module_url="/$language";
}
?>
<script type="text/javascript">
    jQuery(function($) {
        imgs = $("img");
        for (i = 0, n = imgs.length; i < n; i++) {
            $(imgs[i]).parent().attr("href", $(imgs[i]).attr("src"));
            $(imgs[i]).parent().attr("rel", "prettyPhoto");
        }
        
    });
</script>


    
        

			<?php
			$n=count($matHangs);
		         for($i=0;$i<$n;$i++){
                             if($i==0||$i%3==0){
                                 echo '<div class="row-fluid" style="margin-bottom:20px;">';
                             }
                             				                                        
					$loi_gioi_thieu=String1::crop($matHangs[$i]['loi_gioi_thieu_'.$language],30);
					?>
<div class="p_c_item span4 <?php if(false) echo 'background_ie8'; else echo 'background';?>">
                        <a href="<?php echo $this->baseUrl().$language_module_url.'/index/detail/id/'.$matHangs[$i]['id'];?>" id="<?php echo $matHangs[$i]["id"];?>" class="p_c_i_title"><?php echo $matHangs[$i]['title_'.$language];?></a>
                        <a class="p_c_i_img" style="margin-top: 20px;">
                                <?php                                                            
                                Image::echoImage($this->baseUrl($matHangs[$i]['logo']), 200, 200,'height');
                                ?>
                            </a>
                            
                            <p class="p_c_i_subtitle"><?php echo $loi_gioi_thieu;?></p>
                            <p class="p_c_i_des"><?php echo String1::crop(nl2br($matHangs[$i]['mo_ta_'.$language]),80);?>
                            </p>
                            
                                    <a class="view_more" href="<?php echo $this->baseUrl().$language_module_url.'/index/detail/id/'.$matHangs[$i]['id'];?>">
                                        <?php if($language=="vi") echo "Chi tiết"; else if($language=="cn") echo "细节"; else if($language=="en") echo "Detail";?>                                        
                                    </a>
                              
                            
                  </div>
				
				<?php 
				if($i%3==2){
                                 echo '</div> ';
                             }
		         ?>
			

			<?php     
		         }
		         ?>
		
        
    
	

