<script type="text/javascript">
function allowUpload(file){	 
	j=0;
	for(i=file.value.length-1;i>-1;i--)
		if(file.value.charAt(i)=='.')
		{
			j=i;
			break;
		}
	ext="";
	for(i=j+1;i<file.value.length;i++)
		ext+=file.value.charAt(i);	
	ext=ext.toLowerCase();
	a=new Array();	
	a.push("gif");
	a.push("jpg");	
	a.push("jpeg");
	a.push("png");	
    n=a.length;
	for(i=0;i<n;i++)
		if(ext==a.pop()){
			//jQuery("#width").val('');
			//jQuery("#height").val('');
			return;
		}
	jQuery(file).replaceWith("<input type='file' name='logo' onchange='allowUpload(this);'/>");
	file=document.form1.item_image; 
	jQuery(file).css("border-color","red");
	jQuery(file).focus();	
}


function save(){	
	document.form1.submit(); 
}

</script>
<?php
$item=$this->item; 
$message=$this->message;
if($message!=""){
?>
<div class="row-fluid" style="margin-top: 20px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='color: red;'>
        <?php
        echo $message;
        ?>
    </div>
    <div class="span3">&nbsp;</div>
</div>
<?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
	  <div style="float: left;"></div>
	  <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
	  <div style="clear: both;"></div>
	</div>
        
    </div>
    <div class="span3">&nbsp;</div>
</div>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span12" style="text-align: center;font-size: 30px;">Logo</div>    
</div>
<div class="row-fluid">
    <div class="span5">&nbsp;</div>
    <div class="span7">
        <form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->baseUrl('/admin/logo/save');?>" method="post">
	   
	    
	   
	   
	    
            <div class="row-fluid">
                <div class="span12">
               <?php 
               if($item['file_name']!=""){
                   Zend_Loader::loadFile('./../library/Core/Common/Image.php', null, true);
                   Image::echoImage($this->baseUrl($item['file_name']), 70, 70, 'height');              
               }
               else{?>
               <img alt="" src="<?php echo $this->baseUrl('/images/img_photo01.jpg');?>">
               <?php    
               }
               ?>
           </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                <p>                                            
                    <input type="file" name="logo" onchange='allowUpload(this);'/>
                </p>                
                </div>
                </div>
            <div class="row-fluid">
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span2">
                            <input type="radio" value="1" name="dynamic" id="dynamic"<?php if($item['dynamic']=='1') echo ' checked';?>/>
                        </div>
                        <div class="span10">
                            <label for="dynamic">Chuyển động</label>
                        </div>
                        
                
                    </div>
                
                </div>
                <div class="span8">
                    <div class="row-fluid">
                        <div class="span1">
                            <input type="radio" value="0" name="dynamic" id="static"<?php if($item['dynamic']=='0') echo ' checked';?>/>
                        </div>
                        <div class="span11">
                            <label for="static">Đứng yên</label>
                        </div>
                        
                
                    </div>
                
            </div>
                </div>
	        
	</form>
    </div>
    
</div>

