<script type="text/javascript">
function save(){	
	document.form.submit(); 
}
function backItemIndex(){
	url="<?php echo $this->baseUrl('/admin/slide/');?>";
	window.location=url; 
}
  
</script>
<?php
$message=$this->message;
if($message!=""){
?>
<div class="row-fluid" style="margin-top: 20px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='color: red;'>
        <?php
        echo $message;
        ?>
    </div>
    <div class="span3">&nbsp;</div>
</div>
<?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">	  
	  <div onclick="save();" style="float: right;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>
	  <div onclick="backItemIndex();" style="float: right;margin-right: 10px;text-decoration: underline;color: blue;cursor: pointer;">Đóng</div>
	  <div style="clear: both;"></div>
	</div>
        
    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url();?>" method="post">
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span4">&nbsp;</div>
    <div class="span8"><h3>Tiếng Việt</h3></div>
    <div class="span12">
        <?php echo $this->formVi($this,$this->form, 1,$echo_form_tag=FALSE);?>
    </div>
    
</div>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span4">&nbsp;</div>
    <div class="span8"><h3>Tiếng Trung</h3></div>
    <div class="span12">
        <?php echo $this->formCn($this,$this->form, 1,$echo_form_tag=FALSE);?>
    </div>
    
</div>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span4">&nbsp;</div>
    <div class="span8"><h3>Tiếng Anh</h3></div>
    <div class="span12">
        <?php echo $this->formEn($this,$this->form, 1,$echo_form_tag=FALSE);?>
    </div>
    
</div>    


</form>    



