<?php
/**
* @file: default.phtml
* @author: huuthanh3108@gmaill.com
* @date: 05-12-2012
* @company : http://dnict.vn
**/
?>
<!-- CAROUSEL : begin -->
<div class="carousel-container">
	<div class="row">
		<div class="offset1 span10">
			<div id="home-carousel" class="carousel slide loading">
				<!-- ITEMS : begin -->
				<div class="carousel-inner">
				<?php
				for ($i = 0; $i < count($rows); $i++) :
				?>
					<div class="<?php echo ($i==0)?'active':'';?> item">
					<?php
						echo  $rows[$i]['image'];
					?>						
						<div class="carousel-caption">
						<h4><a href="<?php echo $this->view->baseUrl().'/news/index/read/id/'.$rows[$i]['id'];?>"><?php echo $rows[$i]['title'];?></a></h4>
						<em><?php echo $rows[$i]['introtext']?></em>						
						</div>
						</div>						
				<?php
				endfor; 
				?>
				</div>
				<!-- ITEMS : end -->
				<a class="carousel-control left" href="#home-carousel"
					data-slide="prev">&lsaquo;</a> <a class="carousel-control right"
					href="#home-carousel" data-slide="next">&rsaquo;</a> <span
					class="decor leftside">&nbsp;</span> <span class="decor rightside">&nbsp;</span>
			</div>
		</div>
	</div>
</div>
<!-- CAROUSEL : end -->
